# -*- coding: utf-8 -*-
"""240902_hello world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pgSN2DFlSMTpH0vWZGriXI-ju5mgDm-q
"""

print("hello world")

